### ISSUE TITLE
Deploy to a staging server

### ISSUE THREAD

**Issue by damianmarti** [moonshotcollective/recruiter.party#40]

**Comment by Dhaiwat10** [comment]
I can take care of deploying the frontend but I am not sure about the server config. (cookies etc) I can give it a try though. Where do we want to deploy this? Heroku? Vercel?

**Comment by damianmarti** [comment]
I don't have any preference about it. I usually use surge for the frontend because a like the simplicity from surge, but deploy it where you want.

For the server is up to you too. Heroku is ok. I never used Versel, but I think that is ok too. I think the most simpler, the best. I think that is not any uncommon config for it. We can use mongodb from mongodb.com.

**Comment by Dhaiwat10** [comment]
Using surge seems a bit tricky because `next export` doesn't seem to be working:

```md
info  - No "exportPathMap" found in "next.config.js". Generating map from "./pages"
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.
  Possible solutions:
    - Use `next start` to run a server, which includes the Image Optimization API.
    - Use any provider which supports Image Optimization (like Vercel).
    - Configure a third-party loader in `next.config.js`.
    - Use the `loader` prop for `next/image`.
  Read more: https://nextjs.org/docs/messages/export-image-api
    at /Users/dhaiwat/code/recruiter.party/node_modules/next/dist/export/index.js:257:23
    at async Span.traceAsyncFn (/Users/dhaiwat/code/recruiter.party/node_modules/next/dist/telemetry/trace/trace.js:60:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Dhaiwat10** [comment]
Thoughts on using Vercel for this? We would have to install it for the Moonshot org. I could try deploying from personal account using a fork.

**Comment by Dhaiwat10** [comment]
Re. the server, I think Heroku should do the trick? @QEDK any thoughts on that?

**Comment by damianmarti** [comment]
> Re. the server, I think Heroku should do the trick? @QEDK any thoughts on that?

Yes, Heroku is ok. Google Cloud is another option.

**Comment by QEDK** [comment]
> > Re. the server, I think Heroku should do the trick? @QEDK any thoughts on that?
> 
> Yes, Heroku is ok. Google Cloud is another option.

We can redeploy this on Heroku, should be relatively simple, for the frontend I would prefer something else ofc, but anything goes.

**Comment by Dhaiwat10** [comment]
Let's discuss this in tomorrow's call
